<?php
    if ($pagination->isCurrentFirstPage()) {
        $current_url_params = [];
    } else {
        $current_url_params = [
            'page' => $pagination->currentPage(),
        ];
    }

    $this->layout('reading.phtml', [
        'title' => $collection->name(),
        'canonical' => url_full('read list', $current_url_params),
        'current_tab' => $beta_enabled ? 'reading' : 'links',
        'current_page' => 'read',
        'reset_back_options' => $beta_enabled,
    ]);
?>

<div class="section__title">
    <h1><?= protect($collection->name()) ?></h1>
</div>

<p class="section__intro">
    <?= _('Find here all the links you’ve marked as read.') ?>
</p>

<?php if ($pagination->numberElements() > 0): ?>
    <div class="collection__number-links">
        <?= _nf('%s link', '%s links', $pagination->numberElements(), format_number($pagination->numberElements())) ?>
    </div>
<?php endif; ?>

<?php foreach ($links_timeline->datesGroups() as $date_group): ?>
    <section class="group">
        <header class="group__header">
            <h2 class="group__title">
                <?= _date($date_group->date, 'dd MMMM') ?>

                <?php if ($date_group->isToday()): ?>
                    <small class="text--secondary">⋅ <?= _('today') ?></small>
                <?php elseif ($date_group->isYesterday()): ?>
                    <small class="text--secondary">⋅ <?= _('yesterday') ?></small>
                <?php endif; ?>
            </h2>

            <div class="group__separator"></div>
        </header>

        <?php foreach ($date_group->via_groups as $via_group): ?>
            <h3 class="title--small">
                <?= $via_group->title() ?>

                <small class="text--secondary">
                    ⋅ <?= count($via_group->links) ?> liens
                </small>
            </h3>

            <div class="cards">
                <?php foreach ($via_group->links as $link): ?>
                    <?= $this->include('links/_link.phtml', [
                        'link' => $link,
                        'from' => \Minz\Url::for('news'),
                        'display_edit' => true,
                        'display_repair' => true,
                        'display_via' => false,
                        'display_read_later' => true,
                        'display_mark_as_read' => true,
                        'display_never' => true,
                        'storing_must_mark_as_read' => true,
                    ]); ?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </section>
<?php endforeach; ?>

<?= $this->include('_pagination.phtml', ['pagination' => $pagination, 'url' => url('read list')]) ?>

<img
    class="illustration illustration--centered"
    alt=""
    src="<?= url_static('illustrations/collecting.svg') ?>"
    height="250"
/>
